portalService:
  name: portal
  hostname: "localhost"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  image:
    repository: planetariumhq/9c-portal
    tag: "internal-latest"
    pullPolicy: Always
  externalSecret:
    enabled: true
    provider: AWS
    prefix: "9c-internal-v2/portal"
  env:
    ETH_JSON_RPC_PROVIDER_URL: "https://mainnet.infura.io/v3/9b981bb164114a8b882d6c6c6c8d9fc1"
    TWITTER_ID: "1155834450787233792"
    IR2_TWITTER_ID: "1752251826886553600"
    JC_TWITTER_ID: "709049309237346304"
    MINIMUM_BALANCE_TO_WITHDRAW: 5
    NC_ADDRESS_NCG_MINTER: 47d082a115c63e7b58b1532d20e631538eafadde
    NC_ADDRESS_PORTAL: "0x491d9842ed8f1b5d291272cf9e7b66a7b7c90cda"
    NC_ADDRESS_NCG_VOUCHER: "0xc1Ea0D238f7b1C9c70Ce6589DAb2F15C1A076455"
    PLANET_VAULT_ADDRESS: "0x1c2ae97380CFB4F732049e454F6D9A25D4967c6f"
    BACKEND_ROLE_ARN: "arn:aws:iam::319679068466:role/9c-portal-kms"
    KMS_REGION: us-east-2
    KMS_MEAD_REGION: us-east-2
    KMS_NCG_VOUCHER_REGION: us-east-2
    DISCORD_SERVER_ID: "1069427717130440794"
    DISCORD_IR2_SERVER_ID: "1222423353936183359"
    AUTH_COOKIE_NAME: accessToken
    S3_REGION: us-east-2
    MAINNET_ODIN: "https://9c-main-jwt.nine-chronicles.com/graphql"
    MAINNET_HEIMDALL: "https://heimdall-jwt.nine-chronicles.com/graphql"
backofficeService:
  name: backoffice
  hostname: "localhost"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  image:
    repository: planetariumhq/9c-portal-backoffice
    tag: "internal-latest"
    pullPolicy: Always
  externalSecret:
    enabled: true
    provider: AWS
    prefix: "9c-internal-v2/backoffice"
  cronjobs:
